[Consensus]

== 共识

当谈到去中心记录保存时，区块链技术经常被描述，单靠信任来确保事实信息被添加到记录簿中变得不可行。这个问题出现在去中心网络中，因为缺乏一个通常会决定什么应该被视为事实的中心实体。在使用区块链技术时很难避免这个问题，因为缺少一个中央实体是区块链普及的主要贡献者之一。为了避免这个问题，网络必须有一个系统，网络中的节点可以达成共识。

共识协议是一个允许多个网络节点就什么应该被视为事实达成一致的系统。当提及区块链网络时，该协议用于确定区块链的哪个副本是真正的副本。这是防止恶意方欺骗网络并保证区块链完整性的必要条件。区块链技术中使用的共识协议有多种类型，我们将重点关注工作证明（*POW*）和权益证明（*POS*）。

=== POW

工作证明是一个共识协议，认为网络中的有效区块链是创建时计算量最大的链。这里提到的计算工作是为了将所有区块添加到当前区块链而必须完成的工作。这项工作是由网络节点完成的，必须在计算上有困难，以便使工作变得重要，但也必须是可行的，以便在施加合理的努力之后可以实现。最终，网络将依靠提供此POW的节点来维持区块链，并因此符合网络的最佳利益，以便需要合理的POW。

在以太坊网络以及许多其他区块链网络中，获取POW需要找到要添加到区块链的区块的散列。这个散列是通过对由区块的数据和一个随机数组成的字符串进行散列获得的（创建该字符串的方法可能会有所不同，但整个过程是相同的）。这个散列值必须小于某个阈值（由网络难度决定），并且一旦节点出现产生该散列值的随机数，相应的区块将被接受并添加到区块链中。

找到这个有效散列的方式是修改nonce，通常将其初始化为零并在每次迭代时递增，直到产生低于网络阈值的散列值为止。这个过程被称为挖矿。由于挖矿中使用的散列函数的性质，寻找有效随机数的唯一方法是通过暴力破解，即检查每个可能的nonce值，直到找到符合网络要求的散列值。正因如此，提供有效的随机数被认为是一个POW。

=== POS 

权益证明（PoS）是一种公共区块链的共识算法类别，它依赖于验证者在网络中的经济权益。在基于工作证明（PoW）的公共区块链（比如比特币和当前实施的以太坊）中，算法奖励解决密码难题的参与者，以验证交易并创建新的区块（即采矿）。在基于PoS的公共区块链（例如以太坊即将推出的Casper实施方案）中，一组验证者轮流在下一个区块提议并投票，每个验证人投票的权重取决于其存款的大小（即权益）。PoS的显着优势包括安全性、集中化风险降低和能源效率。

一般来说，权益证明算法如下所示。区块链跟踪一组验证者，任何持有区块链基础加密货币（在以太坊的情况下为以太币）的人都可以通过发送一种特殊类型的交易来锁定他们的以太币为存款，从而成为验证者。然后通过所有当前验证者都可以参与的共识算法完成创建和同意新区块的过程。

共识算法有很多种，并且有许多方法可以将奖励分配给参与共识算法的验证者，所以存在许多种风格的权益证明。从算法的角度来看，有两种主要类型：基于链的权益证明和BFT风格的权益证明。

*在基于链的权益证明的情况下，算法在每个时隙中伪随机地选择一个验证器（例如，每个10秒的时间段可能是一个时隙），并为验证者赋予创建单个区块的权利，区块必须指向某个先前的区块（通常是前一个最长链末尾的区块），并且随着时间的推移，大多数区块会聚合成一个不断增长的链。

*在BFT风格的证据中，验证者被随机分配建议区块的权利，但是同意哪个区块是规范的是通过多轮处理来完成的，其中每个验证者在每个回合期间发送对于某个特定区块的“投票”并且在流程结束时，所有（诚实的和在线的）验证器都会永久地同意是否给定的区块是链中的一部分。请注意，区块可能仍然链接在一起; 关键的区别在于，一个区块的共识可以在一个区块内，并且不依赖于它之后的链的长度或大小。

==== POA

权威证明（POA）是主要由测试网络和私有或联盟网络使用的POS共识算法的子集。在基于POA的区块链中，交易有效性最终由一组被认可的链上账户确定，称为“权威节点”。确定权威节点的标准是通过网络治理结构中编纂的方法决定的。

POA被广泛认为是达成共识的最快途径，但依赖于验证节点没有受到损害的假设。非验证参与者可以像访问公共以太坊网络一样访问和使用网络（通过利用P2P交易、合约、账户等）

POA的共识依赖于验证者的声誉和过去的表现。这个想法是，验证者节点将自己的身份/声誉抵押给我。私有联盟网络的一个重要表现是链上地址与已知的真实世界身份之间的联系。因此，我们可以说，验证节点抵押的是他们的“身份”或“声誉”（而不是他们的经济权益）。这为验证器创建了一些级别的问责制，最适合于企业，私人或测试网络。

POA目前由测试网络Kovan（POA网络）使用，并且可以在Parity中为私有联盟网络轻松配置。

==== DPOS

委托权益证明（DPOS）是一种经过修改的权益证明形式，网络参与者投票选举一批代表（也称为证人）来验证和保护区块链。这些代表有点类似于POA中的权威节点，除了他们的权力可能被选民撤销。

在DPOS的共识中，与POS一样，投票的权重与用户注入的权益数量成正比。这创建了一个场景，其中较大的代币持有者比较小的代币持有者拥有更高比例的投票权。这从游戏理论的角度来看是有意义的，因为权益拥有者最有动力选择最有效的代表。

另外，代表证人会收到验证每个区块的奖励，因此激励他们保持诚实和有效率 - 以便不被替换。但是，有些方法可能会产生相当合理的“贿赂”; 例如，交易所可以为存款提供利率（或者，甚至更模糊地使用交易所自己的资金来建立良好的界面和特征），交易所运营商使用大量存款在DPOS中按照他们的意愿进行投票共识。


== 以太坊的共识

=== Ethash简介

Ethash是以太坊的 *工作证明(PoW)算法* ，它依赖于初始时期生成的大小约为1GB的数据集的，称为有向无环图 (*DAG*) 。 *DAG* 使用了 *Dagger-Hashimoto算法* 的一个版本，它是 *Vitalik Buterin's Dagger算法* 和 *Thaddeus Dryja's Hashimoto算法* 的组合。 *Dagger-Hashimoto算法* 是Ethereum 1.0使用的挖矿算法。随着时间的推移， *DAG* 线性增长，并且每个 *纪元*（30,000块，125小时）更新一次。

==== 种子、缓存、数据生成

*PoW算法* 包括: +
 -  通过扫描 *DAG* 的前面的区块头为每个区块计算 *种子* 。 +
 -  *Cache* 是一个16MB的伪随机缓存，根据种子计算出来，存储在轻量客户端中。 +
 -  *DAG*的 *数据生成* 来自缓存，用于存储在完整客户端和矿工上（数据集中的每个项目仅依赖于缓存中的少量项目）。 +
 -  *矿工* 通过对数据集进行随机切片并将它们散列在一起进行挖矿。可以使用存储的高速缓存和低内存来执行验证，以重新生成所需数据集的特定部分。

.References：
 -  Ethash-DAG：https://github.com/ethereum/wiki/wiki/Ethash-DAG
 -  Ethash规范：https://github.com/ethereum/wiki/wiki/Ethash
 - 挖矿Ethash DAG：https://github.com/ethereum/wiki/wiki/Mining#ethash-dag
 -  Dagger-Hashimoto算法：https://github.com/ethereum/wiki/blob/master/Dagger-Hashimoto.md
 -  DAG说明和镜像：https://ethereum.stackexchange.com/questions/1993/what-actually-is-a-dag
 -  以太坊黄皮书中的Ethersh：https://ethereum.github.io/yellowpaper/paper.pdf#appendix.J
 -  Ethash C API示例用法：https://github.com/ethereum/wiki/wiki/Ethash-C-API

==== POW功能 

==== 为什么GPU很重要？


=== 卡斯帕简介 

==== POS
POS共识算法预计将在该项目中引入，POS功能如上所述。

==== Slash协议

TODO


=== 介绍Polkadot

Polkadot是一个链间区块链协议，将包括与权益证明（POS）区块链的集成，允许parachain在没有内部共识的情况下达成共识。 

.Polkadot包括：
 -  *中继链* 连接到所有的Parachains并协调构成区块链之间的共识和交易传递，并使用 *验证功能* 通过验证PoV区块候选的正确性来促进完成Parachain交易。
 -  *Parachains*（跨网络的并行链），它们是组成区块链，收集并平行处理事务以实现可伸缩性。 
 -  *Trust-free Transaction Relaying(去信任交易中继)* 构成区块链之间直接进行信任交易中继，而不是通过中介或去中心交易所。
 -  *Pooled Security*，用于根据一致性协议规则 (*规则*) 检查Parachain交易有效性。通过动态治理系统绑定每个集团成员的一定比例的权益代币，从而实现安全。组成员资格要求绑定来自验证者和提名者的权益代币做输入，这些输入可能在不良行为的情况下被扣除。
 -  *Bridges* 通过解耦具有不同共识体系结构机制的区块链网络之间的链接来提供可扩展性。
 -  *Collators* 负责通过将其可用交易整合到有效性证明（PoV）候选区块中来管理和维护特定的Parachain，向验证人报告以证明交易是有效的，并在区块中正确执行。如果获奖机票（由Collator最接近Polkadot地址的黄金机票签署）并成为规范并最终确定，则会鼓励协会成员支付从创建PoV候选区块收取的任何交易费用。校友会获得Polkadot地址。专业人员不会使用标记。
 -  *Golden Ticket* 是每个包含奖励的每个Parachain中的特定Polkadot地址。校准器被赋予一个Polkadot地址，并将校验器与由Collator签名的PoV候选块进行校验。奖励获胜者在PoV候选区块中有一个Collator Polkadot地址，该地址接近Golden Ticket Polkadot地址
 -  *Collators* 监测Polkadot网络交易以发现Polkadot社区中的不良行为。将验证人带到法庭并证明他们表现不佳的渔夫，将被验证人债券的一部分激励，因为债券被用作惩罚来支付不良行为。
 -  *验证者* ，它们是Parachain社区中的维护人员，他们被部署到不同的Parachains中来监控系统。验证人同意Merkle Trees的根源。验证人必须使交易可用。验渔人可能会被渔夫带到法庭进行交易可用和相关联的调查员可能会质疑交易是否有可用的Collat​​or证明。
 -  *提名者* （与PoW采矿公司类似）被动地监督并投票认定他们认为可以通过为股票代币提供资金而接受的验证人。

Polkadot的中继链使用一个 *证明权益(PoS)* 系统，其中结构化状态机（SM）并行地执行多个拜占庭容错（BFT）一致性'，以便SM进步收敛于包含有效候选者的解决方案块跨越多个Parachain维度。由于根据共识机制，目标验证器（下一个块）只有在源验证器（前一个块）具有足够的事务信息时才可以实施传入消息，因此根据事务的可用性和有效性来确定每个Parachain中的有效候选块可用和有效。验证方投票选出由校稿人使用规则达成共识的有效候选区块。

.References
 -  Polkadot链接：https://polkadot.network
 -  柏林Parity以太坊Polkadot演示链接：https://www.youtube.com/watch?v=gbXEcNTgNco
